before_script:
  - ln -s /builds /go/src/$(echo "github.com/StackFocus/SwagIP-go" | cut -d "/" -f1)
  - cd /go/src/github.com/StackFocus/SwagIP-go
  - mkdir -p public/assets
  - go get -u github.com/gobuffalo/buffalo/buffalo
  - go get -t -v ./...
  - export PATH="$PATH:$GOPATH/bin"

stages:
  - test

.test-vars: &test-vars
  variables:
    GO_ENV: "test"

# Golang version choice helper
.use-golang-image: &use-golang-latest
  image: golang:latest

.use-golang-image: &use-golang-1-8
  image: golang:1.8

test:
  # Change to "<<: *use-golang-latest" to use the latest Go version
  <<: *use-golang-latest
  <<: *test-vars
  stage: test
  script:
    - buffalo test
