language: go

go:
  - master

env:
  - GO_ENV=test
  - GO111MODULE=on

before_script:
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets

go_import_path: github.com/StackFocus/SwagIP-go

install:
  - go get github.com/gobuffalo/buffalo/buffalo
  - go get $(go list ./... | grep -v /vendor/)

script: buffalo test
